// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShopSolution.WebApp.Entities;

namespace eShopSolution.WebApp.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eShopSolution.WebApp.Entities.CTDH", b =>
                {
                    b.Property<int>("SoCT")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaDH");

                    b.Property<int>("MaSach");

                    b.Property<int>("SoLuong");

                    b.HasKey("SoCT");

                    b.HasIndex("MaDH");

                    b.HasIndex("MaSach");

                    b.ToTable("CTDH");
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ID");

                    b.Property<int>("MaKH");

                    b.Property<DateTime>("NgayDat");

                    b.Property<string>("NoiGiao");

                    b.Property<int>("TinhTrang");

                    b.HasKey("MaDH");

                    b.HasIndex("ID");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.GioHang", b =>
                {
                    b.Property<int>("MaGH")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ID");

                    b.Property<int>("MaKH");

                    b.Property<int>("MaSach");

                    b.Property<int>("SoLuong");

                    b.HasKey("MaGH");

                    b.HasIndex("ID");

                    b.HasIndex("MaSach");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.LoaiSach", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSach");
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Gia");

                    b.Property<int?>("GioHangMaGH");

                    b.Property<string>("Hinh");

                    b.Property<int>("MaLoai");

                    b.Property<string>("MoTa");

                    b.Property<string>("TacGia");

                    b.Property<string>("TenSach");

                    b.HasKey("MaSach");

                    b.HasIndex("GioHangMaGH");

                    b.HasIndex("MaLoai");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("Email");

                    b.Property<string>("HoTen");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.Property<string>("SDT");

                    b.HasKey("ID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.CTDH", b =>
                {
                    b.HasOne("eShopSolution.WebApp.Entities.DonHang", "DonHang")
                        .WithMany("CTDHs")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("eShopSolution.WebApp.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.DonHang", b =>
                {
                    b.HasOne("eShopSolution.WebApp.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("ID");
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.GioHang", b =>
                {
                    b.HasOne("eShopSolution.WebApp.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("ID");

                    b.HasOne("eShopSolution.WebApp.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("eShopSolution.WebApp.Entities.Sach", b =>
                {
                    b.HasOne("eShopSolution.WebApp.Entities.GioHang")
                        .WithMany("Sachs")
                        .HasForeignKey("GioHangMaGH");

                    b.HasOne("eShopSolution.WebApp.Entities.LoaiSach", "LoaiSach")
                        .WithMany("Sachs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
